<?php

namespace Uom\UomUi\Theme;

use Illuminate\Support\Facades\File;
use RuntimeException;
use Symfony\Component\Process\Process;

class ThemeBuilder
{
    protected string $packageRoot;

    public function __construct()
    {
        $this->packageRoot = dirname(__DIR__, 2);
    }

    /**
     * Build the complete UomUI theme.
     */
    public function build(): array
    {
        $this->ensureRequirements();

        $themeFile = $this->generateThemeScss();

        // Build normal LTR CSS.
        $this->compileCss();

        // Generate RTL version from the freshly compiled CSS.
        $this->compileRtlCss();

        // Publish both versions to the Laravel application.
        $publishedFiles = $this->publishCss();

        return [
            'theme_file' => $themeFile,
            'published_files' => $publishedFiles,
        ];
    }

    /**
     * Generate Bootstrap Sass variable overrides
     * from config/uomuitheme.php.
     */
    protected function generateThemeScss(): string
    {
        $theme = config('uomuitheme.colors.theme', []);

        $variables = [
            'primary',
            'secondary',
            'success',
            'danger',
            'warning',
            'info',
            'light',
            'dark',
        ];

        $scss = [];

        $scss[] = '// -----------------------------------------------------------------------------';
        $scss[] = '// UomUI Generated Theme';
        $scss[] = '// -----------------------------------------------------------------------------';
        $scss[] = '// DO NOT EDIT THIS FILE MANUALLY.';
        $scss[] = '// Generated from config/uomuitheme.php';
        $scss[] = '// Run: php artisan uomui:build';
        $scss[] = '// -----------------------------------------------------------------------------';
        $scss[] = '';

        /*
        |--------------------------------------------------------------------------
        | Theme Colors
        |--------------------------------------------------------------------------
        */

        foreach ($variables as $variable) {
            $value = $theme[$variable] ?? null;

            if ($value !== null) {
                $this->validateCssValue(
                    "colors.theme.{$variable}",
                    $value
                );

                $scss[] = "\${$variable}: {$value};";
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Semantic Colors
        |--------------------------------------------------------------------------
        */

        $semanticMappings = [
            'body.color' => 'body-color',
            'body.background' => 'body-bg',

            'secondary.color' => 'secondary-color',
            'secondary.background' => 'secondary-bg',

            'tertiary.color' => 'tertiary-color',
            'tertiary.background' => 'tertiary-bg',

            'emphasis.color' => 'emphasis-color',

            'border.color' => 'border-color',
            'border.translucent' => 'border-color-translucent',

            'link.color' => 'link-color',
            'link.hover' => 'link-hover-color',
        ];

        foreach ($semanticMappings as $configKey => $sassVariable) {
            $value = config(
                "uomuitheme.colors.semantic.{$configKey}"
            );

            if ($value !== null) {
                $this->validateCssValue(
                    "colors.semantic.{$configKey}",
                    $value
                );

                $scss[] = "\${$sassVariable}: {$value};";
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Typography
        |--------------------------------------------------------------------------
        */

        $typographyMappings = [
            'body.font_size' => 'font-size-base',
            'body.font_weight' => 'font-weight-base',
            'body.line_height' => 'line-height-base',

            'headings.font_weight' => 'headings-font-weight',
            'headings.line_height' => 'headings-line-height',
            'headings.color' => 'headings-color',

            'headings.h1.font_size' => 'h1-font-size',
            'headings.h2.font_size' => 'h2-font-size',
            'headings.h3.font_size' => 'h3-font-size',
            'headings.h4.font_size' => 'h4-font-size',
            'headings.h5.font_size' => 'h5-font-size',
            'headings.h6.font_size' => 'h6-font-size',

            'small.font_size' => 'small-font-size',

            'lead.font_size' => 'lead-font-size',
            'lead.font_weight' => 'lead-font-weight',
        ];

        foreach ($typographyMappings as $configKey => $sassVariable) {
            $value = config(
                "uomuitheme.typography.{$configKey}"
            );

            if ($value !== null) {
                $this->validateCssValue(
                    "typography.{$configKey}",
                    $value
                );

                $scss[] = "\${$sassVariable}: {$value};";
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Borders
        |--------------------------------------------------------------------------
        */

        $borderMappings = [
            'width' => 'border-width',
            'style' => 'border-style',
            'color' => 'border-color',
            'translucent' => 'border-color-translucent',
        ];

        foreach ($borderMappings as $configKey => $sassVariable) {
            $value = config(
                "uomuitheme.borders.{$configKey}"
            );

            if ($value !== null) {
                $this->validateCssValue(
                    "borders.{$configKey}",
                    $value
                );

                $scss[] = "\${$sassVariable}: {$value};";
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Border Radius
        |--------------------------------------------------------------------------
        */

        $radiusMappings = [
            'default' => 'border-radius',
            'sm' => 'border-radius-sm',
            'lg' => 'border-radius-lg',
            'xl' => 'border-radius-xl',
            'xxl' => 'border-radius-xxl',
            'pill' => 'border-radius-pill',
        ];

        foreach ($radiusMappings as $configKey => $sassVariable) {
            $value = config(
                "uomuitheme.rounded.{$configKey}"
            );

            if ($value !== null) {
                $this->validateCssValue(
                    "rounded.{$configKey}",
                    $value
                );

                $scss[] = "\${$sassVariable}: {$value};";
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Shadows
        |--------------------------------------------------------------------------
        */

        $shadowMappings = [
            'sm' => 'box-shadow-sm',
            'default' => 'box-shadow',
            'lg' => 'box-shadow-lg',
            'inset' => 'box-shadow-inset',
        ];

        foreach ($shadowMappings as $configKey => $sassVariable) {
            $value = config(
                "uomuitheme.shadows.{$configKey}"
            );

            if ($value !== null) {
                $this->validateCssValue(
                    "shadows.{$configKey}",
                    $value
                );

                $scss[] = "\${$sassVariable}: {$value};";
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Spacing
        |--------------------------------------------------------------------------
        */

        $spacer = config('uomuitheme.spacing.base');

        if ($spacer !== null) {
            $this->validateCssValue(
                'spacing.base',
                $spacer
            );

            $scss[] = "\$spacer: {$spacer};";
        }

        /*
        |--------------------------------------------------------------------------
        | Bootstrap Options
        |--------------------------------------------------------------------------
        */

        $optionMappings = [
            'rounded' => 'enable-rounded',
            'shadows' => 'enable-shadows',
            'gradients' => 'enable-gradients',
            'transitions' => 'enable-transitions',
        ];

        foreach ($optionMappings as $configKey => $sassVariable) {
            $value = config(
                "uomuitheme.options.{$configKey}"
            );

            if ($value !== null) {
                $scss[] = "\${$sassVariable}: "
                    . ($value ? 'true' : 'false')
                    . ';';
            }
        }

        $scss[] = '';

        $path = $this->packageRoot
            . '/resources/scss/generated/_theme.scss';

        File::ensureDirectoryExists(
            dirname($path)
        );

        File::put(
            $path,
            implode(PHP_EOL, $scss) . PHP_EOL
        );

        return $path;
    }

    /**
     * Compile normal LTR CSS with Sass.
     */
    protected function compileCss(): void
    {
        $this->runNpmScript(
            'build:css',
            'UomUI Sass build failed.'
        );
    }

    /**
     * Generate RTL CSS from the freshly built LTR CSS.
     */
    protected function compileRtlCss(): void
    {
        $source = $this->packageRoot
            . '/dist/css/uomui.css';

        if (! File::exists($source)) {
            throw new RuntimeException(
                "Cannot build RTL CSS because LTR CSS was not found at [{$source}]."
            );
        }

        $this->runNpmScript(
            'build:rtl',
            'UomUI RTL build failed.'
        );
    }

    /**
     * Execute an npm script inside the UomUI package.
     */
    protected function runNpmScript(
        string $script,
        string $errorMessage
    ): void {
        $process = new Process(
            ['npm', 'run', $script],
            $this->packageRoot
        );

        $process->setTimeout(null);

        $process->run();

        if (! $process->isSuccessful()) {
            throw new RuntimeException(
                $errorMessage
                . PHP_EOL
                . PHP_EOL
                . $process->getErrorOutput()
                . $process->getOutput()
            );
        }
    }

    /**
     * Publish generated CSS assets to the consuming Laravel app.
     */
    protected function publishCss(): array
    {
        $files = [
            'uomui.css',
            'uomui.css.map',
            'uomui.rtl.css',
        ];

        $published = [];

        foreach ($files as $file) {
            $source = $this->packageRoot
                . "/dist/css/{$file}";

            if (! File::exists($source)) {
                // Source map is optional.
                if ($file === 'uomui.css.map') {
                    continue;
                }

                throw new RuntimeException(
                    "Generated UomUI asset was not found at [{$source}]."
                );
            }

            $destination = public_path(
                "vendor/uomui/css/{$file}"
            );

            File::ensureDirectoryExists(
                dirname($destination)
            );

            File::copy(
                $source,
                $destination
            );

            $published[] = $destination;
        }

        return $published;
    }

    /**
     * Check required Node packages.
     */
    protected function ensureRequirements(): void
    {
        $packageJson = $this->packageRoot
            . '/package.json';

        if (! File::exists($packageJson)) {
            throw new RuntimeException(
                "UomUI package.json was not found at [{$packageJson}]."
            );
        }

        $nodeModules = $this->packageRoot
            . '/node_modules';

        if (! File::isDirectory($nodeModules)) {
            throw new RuntimeException(
                "UomUI Node dependencies are not installed."
                . PHP_EOL
                . "Run:"
                . PHP_EOL
                . "cd {$this->packageRoot}"
                . PHP_EOL
                . "npm install"
            );
        }

        $sass = $this->packageRoot
            . '/node_modules/sass';

        if (! File::isDirectory($sass)) {
            throw new RuntimeException(
                'Sass is not installed. Run: npm install'
            );
        }

        $bootstrap = $this->packageRoot
            . '/node_modules/bootstrap';

        if (! File::isDirectory($bootstrap)) {
            throw new RuntimeException(
                'Bootstrap is not installed. Run: npm install'
            );
        }

        $rtlCss = $this->packageRoot
            . '/node_modules/rtlcss';

        if (! File::isDirectory($rtlCss)) {
            throw new RuntimeException(
                'RTLCSS is not installed. Run: npm install'
            );
        }
    }

    /**
     * Reject invalid/empty configuration values.
     */
    protected function validateCssValue(
        string $name,
        mixed $value
    ): void {
        if (! is_string($value) && ! is_numeric($value)) {
            throw new RuntimeException(
                "Invalid theme configuration value [{$name}]."
            );
        }

        if (
            is_string($value)
            && trim($value) === ''
        ) {
            throw new RuntimeException(
                "Empty theme configuration value [{$name}]."
            );
        }
    }
}