<!DOCTYPE html>
<html lang="ar" dir="rtl">

<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>UomUI Playground</title>

    {{-- ============================================================
        UomUI CSS

        Generated by:
        php artisan uomui:build

        This already contains Bootstrap + UomUI theme.
    ============================================================= --}}
    <link rel="stylesheet" href="{{ asset('vendor/uomui/css/uomui.rtl.css') }}">
</head>

<body>

    {{-- ============================================================
        Navbar
    ============================================================= --}}
    <nav class="navbar navbar-expand-lg bg-primary navbar-dark">
        <div class="container">

            <a class="navbar-brand fw-bold" href="#">
                UomUI
            </a>

            <span class="navbar-text text-white">
                Theme Playground
            </span>

        </div>
    </nav>


    <main class="container py-5">
        <section class="mb-5">

            <h1 class="display-4 fw-bold">
                اختبار واجهة UomUI العربية
            </h1>

            <p class="lead">
                هذه الصفحة مخصصة لاختبار دعم الاتجاه من اليمين إلى اليسار.
            </p>

            <div class="alert alert-primary">
                هذا مثال لاختبار الألوان والمحاذاة والاتجاه في واجهة RTL.
            </div>

        </section>

        {{-- ========================================================
            Header
        ========================================================= --}}
        <section class="mb-5">

            <h1 class="display-4 fw-bold">
                UomUI Theme Playground
            </h1>

            <p class="lead">
                Visual test page for UomUI and Bootstrap theme settings.
            </p>

            <div class="alert alert-light border">
                Edit
                <code>config/uomuitheme.php</code>
                and run
                <code>php artisan uomui:build</code>
                to rebuild the theme.
            </div>

        </section>


        {{-- ========================================================
            Theme Colors
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Theme Colors
            </h2>

            <div class="row g-3">

                @foreach ([
                'primary',
                'secondary',
                'success',
                'danger',
                'warning',
                'info',
                'light',
                'dark'
                ] as $color)

                <div class="col-6 col-md-4 col-lg-3">

                    <div class="
                                bg-{{ $color }}
                                {{ in_array($color, ['warning', 'info', 'light']) ? 'text-dark' : 'text-white' }}
                                border
                                rounded
                                p-4
                                h-100
                            ">
                        <strong>
                            {{ ucfirst($color) }}
                        </strong>

                        <div class="small mt-2">
                            .bg-{{ $color }}
                        </div>
                    </div>

                </div>

                @endforeach

            </div>

        </section>


        {{-- ========================================================
            Buttons
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Bootstrap Buttons
            </h2>

            <div class="d-flex flex-wrap gap-2">

                @foreach ([
                'primary',
                'secondary',
                'success',
                'danger',
                'warning',
                'info',
                'light',
                'dark'
                ] as $variant)

                <button type="button" class="btn btn-{{ $variant }}">
                    {{ ucfirst($variant) }}
                </button>

                @endforeach

            </div>

        </section>


        {{-- ========================================================
            UomUI Button Component
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                UomUI Button Component
            </h2>

            <div class="d-flex flex-wrap gap-2">

                <x-uomui::button variant="primary">
                    Primary
                </x-uomui::button>

                <x-uomui::button variant="secondary">
                    Secondary
                </x-uomui::button>

                <x-uomui::button variant="success">
                    Success
                </x-uomui::button>

                <x-uomui::button variant="danger">
                    Danger
                </x-uomui::button>

                <x-uomui::button variant="warning">
                    Warning
                </x-uomui::button>

                <x-uomui::button variant="info">
                    Info
                </x-uomui::button>

                <x-uomui::button variant="dark">
                    Dark
                </x-uomui::button>

            </div>

        </section>


        {{-- ========================================================
            Outline Buttons
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Outline Buttons
            </h2>

            <div class="d-flex flex-wrap gap-2">

                @foreach ([
                'primary',
                'secondary',
                'success',
                'danger',
                'warning',
                'info',
                'light',
                'dark'
                ] as $variant)

                <button type="button" class="btn btn-outline-{{ $variant }}">
                    {{ ucfirst($variant) }}
                </button>

                @endforeach

            </div>

        </section>


        {{-- ========================================================
            Button States
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Button States
            </h2>

            <div class="d-flex flex-wrap gap-2">

                <button class="btn btn-primary">
                    Normal
                </button>

                <button class="btn btn-primary active">
                    Active
                </button>

                <button class="btn btn-primary" disabled>
                    Disabled
                </button>

                <button class="btn btn-primary btn-sm">
                    Small
                </button>

                <button class="btn btn-primary btn-lg">
                    Large
                </button>

            </div>

        </section>


        {{-- ========================================================
            Typography
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Typography
            </h2>

            <div class="card">
                <div class="card-body">

                    <h1>Heading H1</h1>
                    <h2>Heading H2</h2>
                    <h3>Heading H3</h3>
                    <h4>Heading H4</h4>
                    <h5>Heading H5</h5>
                    <h6>Heading H6</h6>

                    <hr>

                    <p>
                        This is normal body text used to test the
                        default font size, weight, line height and color.
                    </p>

                    <p class="lead">
                        This is lead text.
                    </p>

                    <p class="small">
                        This is small text.
                    </p>

                    <p class="text-body-secondary">
                        This is secondary body text.
                    </p>

                    <p class="text-body-tertiary">
                        This is tertiary body text.
                    </p>

                    <p>
                        This is a
                        <a href="#">
                            normal link
                        </a>
                        for testing link colors and hover state.
                    </p>

                    <p>
                        Command example:
                        <code>php artisan uomui:build</code>
                    </p>

                </div>
            </div>

        </section>


        {{-- ========================================================
            Text Colors
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Text Colors
            </h2>

            @foreach ([
            'primary',
            'secondary',
            'success',
            'danger',
            'warning',
            'info',
            'dark'
            ] as $color)

            <p class="text-{{ $color }} fw-semibold">
                .text-{{ $color }}
            </p>

            @endforeach

        </section>


        {{-- ========================================================
            Alerts
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Alerts
            </h2>

            @foreach ([
            'primary',
            'secondary',
            'success',
            'danger',
            'warning',
            'info',
            'light',
            'dark'
            ] as $variant)

            <div class="alert alert-{{ $variant }}" role="alert">
                <strong>
                    {{ ucfirst($variant) }}
                </strong>

                alert example generated from the current theme.
            </div>

            @endforeach

        </section>


        {{-- ========================================================
            Badges
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Badges
            </h2>

            <div class="d-flex flex-wrap gap-2">

                @foreach ([
                'primary',
                'secondary',
                'success',
                'danger',
                'warning',
                'info',
                'light',
                'dark'
                ] as $variant)

                <span class="badge text-bg-{{ $variant }}">
                    {{ ucfirst($variant) }}
                </span>

                @endforeach

            </div>

        </section>


        {{-- ========================================================
            Borders
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Border Colors
            </h2>

            <div class="row g-3">

                @foreach ([
                'primary',
                'secondary',
                'success',
                'danger',
                'warning',
                'info'
                ] as $color)

                <div class="col-md-4 col-lg-2">

                    <div class="
                                border
                                border-{{ $color }}
                                border-3
                                rounded
                                p-4
                                text-center
                            ">
                        {{ ucfirst($color) }}
                    </div>

                </div>

                @endforeach

            </div>

        </section>


        {{-- ========================================================
            Radius
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Border Radius
            </h2>

            <div class="row g-3">

                <div class="col-md-3">
                    <div class="border p-4">
                        No rounded
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="border rounded p-4">
                        Rounded
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="border rounded-4 p-4">
                        Rounded 4
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="border rounded-pill p-4 text-center">
                        Pill
                    </div>
                </div>

            </div>

        </section>


        {{-- ========================================================
            Shadows
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Shadows
            </h2>

            <div class="row g-4">

                <div class="col-md-4">
                    <div class="p-4 border rounded shadow-sm">
                        shadow-sm
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="p-4 border rounded shadow">
                        shadow
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="p-4 border rounded shadow-lg">
                        shadow-lg
                    </div>
                </div>

            </div>

        </section>


        {{-- ========================================================
            Cards
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Cards
            </h2>

            <div class="row g-4">

                <div class="col-md-4">

                    <div class="card h-100">

                        <div class="card-header">
                            Default Card
                        </div>

                        <div class="card-body">

                            <h5 class="card-title">
                                Card title
                            </h5>

                            <p class="card-text">
                                Test card for borders, typography,
                                background and spacing.
                            </p>

                            <button class="btn btn-primary">
                                Action
                            </button>

                        </div>

                    </div>

                </div>


                <div class="col-md-4">

                    <div class="card border-primary h-100">

                        <div class="card-header text-bg-primary">
                            Primary Card
                        </div>

                        <div class="card-body">

                            <h5 class="card-title">
                                Primary Theme
                            </h5>

                            <p class="card-text">
                                Useful for checking the primary color
                                throughout multiple Bootstrap components.
                            </p>

                        </div>

                    </div>

                </div>


                <div class="col-md-4">

                    <div class="card shadow h-100">

                        <div class="card-body">

                            <h5 class="card-title">
                                Shadow Card
                            </h5>

                            <p class="card-text">
                                Used to test global shadow configuration.
                            </p>

                        </div>

                    </div>

                </div>

            </div>

        </section>


        {{-- ========================================================
            Forms
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Forms
            </h2>

            <div class="card">

                <div class="card-body">

                    <div class="row g-4">

                        <div class="col-md-6">

                            <label for="testName" class="form-label">
                                Name
                            </label>

                            <input type="text" id="testName" class="form-control" placeholder="Enter your name">

                        </div>


                        <div class="col-md-6">

                            <label for="testSelect" class="form-label">
                                Select
                            </label>

                            <select id="testSelect" class="form-select">
                                <option selected>
                                    Choose...
                                </option>

                                <option>Option 1</option>
                                <option>Option 2</option>
                            </select>

                        </div>


                        <div class="col-12">

                            <label for="testTextarea" class="form-label">
                                Message
                            </label>

                            <textarea id="testTextarea" class="form-control" rows="3"
                                placeholder="Write something..."></textarea>

                        </div>


                        <div class="col-md-6">

                            <label class="form-label">
                                Valid Input
                            </label>

                            <input type="text" class="form-control is-valid" value="Valid value">

                            <div class="valid-feedback">
                                Looks good.
                            </div>

                        </div>


                        <div class="col-md-6">

                            <label class="form-label">
                                Invalid Input
                            </label>

                            <input type="text" class="form-control is-invalid" value="Invalid value">

                            <div class="invalid-feedback">
                                Please correct this value.
                            </div>

                        </div>


                        <div class="col-12">

                            <div class="form-check">

                                <input class="form-check-input" type="checkbox" id="testCheck" checked>

                                <label class="form-check-label" for="testCheck">
                                    Checkbox
                                </label>

                            </div>

                        </div>


                        <div class="col-12">

                            <label for="testRange" class="form-label">
                                Range
                            </label>

                            <input type="range" class="form-range" id="testRange">

                        </div>

                    </div>

                </div>

            </div>

        </section>


        {{-- ========================================================
            Table
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Tables
            </h2>

            <div class="table-responsive">

                <table class="table table-striped table-hover table-bordered">

                    <thead class="table-primary">

                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>

                    </thead>

                    <tbody>

                        <tr>
                            <td>1</td>

                            <td>
                                Example One
                            </td>

                            <td>
                                <span class="badge text-bg-success">
                                    Active
                                </span>
                            </td>

                            <td>
                                <button class="btn btn-sm btn-primary">
                                    Edit
                                </button>
                            </td>
                        </tr>


                        <tr>
                            <td>2</td>

                            <td>
                                Example Two
                            </td>

                            <td>
                                <span class="badge text-bg-warning">
                                    Pending
                                </span>
                            </td>

                            <td>
                                <button class="btn btn-sm btn-danger">
                                    Delete
                                </button>
                            </td>
                        </tr>

                    </tbody>

                </table>

            </div>

        </section>


        {{-- ========================================================
            Progress
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Progress Bars
            </h2>

            <p class="text-body-secondary">
                This section is important for verifying that the rebuilt
                Bootstrap utilities use the new theme colors.
            </p>

            <div class="progress mb-3" role="progressbar" aria-label="Primary progress" aria-valuenow="75"
                aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar bg-primary" style="width: 75%">
                    Primary 75%
                </div>
            </div>


            <div class="progress mb-3" role="progressbar" aria-label="Success progress" aria-valuenow="60"
                aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar bg-success" style="width: 60%">
                    Success 60%
                </div>
            </div>


            <div class="progress" role="progressbar" aria-label="Danger progress" aria-valuenow="40" aria-valuemin="0"
                aria-valuemax="100">
                <div class="progress-bar bg-danger" style="width: 40%">
                    Danger 40%
                </div>
            </div>

        </section>


        {{-- ========================================================
            List Group
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                List Group
            </h2>

            <div class="list-group">

                <a href="#" class="list-group-item list-group-item-action active">
                    Active item
                </a>

                <a href="#" class="list-group-item list-group-item-action">
                    Normal item
                </a>

                <a href="#" class="list-group-item list-group-item-action list-group-item-primary">
                    Primary item
                </a>

                <a href="#" class="list-group-item list-group-item-action list-group-item-success">
                    Success item
                </a>

            </div>

        </section>


        {{-- ========================================================
            Pagination
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Pagination
            </h2>

            <nav aria-label="Pagination test">

                <ul class="pagination">

                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            Previous
                        </a>
                    </li>

                    <li class="page-item active">
                        <a class="page-link" href="#">
                            1
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" href="#">
                            2
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" href="#">
                            3
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" href="#">
                            Next
                        </a>
                    </li>

                </ul>

            </nav>

        </section>


        {{-- ========================================================
            Dropdown
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Dropdown
            </h2>

            <div class="dropdown">

                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Open Dropdown
                </button>

                <ul class="dropdown-menu">

                    <li>
                        <a class="dropdown-item" href="#">
                            Action
                        </a>
                    </li>

                    <li>
                        <a class="dropdown-item" href="#">
                            Another action
                        </a>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item" href="#">
                            Something else
                        </a>
                    </li>

                </ul>

            </div>

        </section>


        {{-- ========================================================
            Modal
        ========================================================= --}}
        <section class="mb-5">

            <h2 class="mb-4">
                Modal
            </h2>

            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#testModal">
                Open Modal
            </button>

        </section>


        {{-- ========================================================
            Build Information
        ========================================================= --}}
        <section class="border-top pt-4">

            <h2 class="h5">
                Theme Build
            </h2>

            <p class="mb-1">
                Configuration:
                <code>config/uomuitheme.php</code>
            </p>

            <p class="mb-1">
                Build command:
                <code>php artisan uomui:build</code>
            </p>

            <p class="mb-0">
                Generated CSS:
                <code>public/vendor/uomui/css/uomui.css</code>
            </p>

        </section>

    </main>


    {{-- ============================================================
        Modal
    ============================================================= --}}
    <div class="modal fade" id="testModal" tabindex="-1" aria-labelledby="testModalLabel" aria-hidden="true">

        <div class="modal-dialog modal-dialog-centered">

            <div class="modal-content">

                <div class="modal-header">

                    <h1 class="modal-title fs-5" id="testModalLabel">
                        UomUI Modal
                    </h1>

                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>

                </div>

                <div class="modal-body">

                    <p>
                        This modal verifies that the UomUI JavaScript
                        bundle and Bootstrap JavaScript are working.
                    </p>

                    <div class="alert alert-primary mb-0">
                        Primary theme test inside the modal.
                    </div>

                </div>

                <div class="modal-footer">

                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        Close
                    </button>

                    <button type="button" class="btn btn-primary">
                        Save
                    </button>

                </div>

            </div>

        </div>

    </div>


    {{-- ============================================================
        UomUI JavaScript
        Includes Bootstrap JavaScript.
    ============================================================= --}}
    <script src="{{ asset('vendor/uomui/js/uomui.js') }}"></script>

</body>

</html>